/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2024-03-08 15:55:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src.main.webapp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n    <head>\r\n        <!-- General meta information -->\r\n        <title>Login Form</title>\r\n        <meta name=\"keywords\" content=\"\" />\r\n        <meta name=\"description\" content=\"\" />\r\n        <meta name=\"robots\" content=\"index, follow\" />\r\n        <meta charset=\"utf-8\" />\r\n        <!-- // General meta information -->\r\n        <!-- Load Javascript -->\r\n        <script type=\"text/javascript\" src=\"./js/jquery.js\"></script>\r\n        <script type=\"text/javascript\" src=\"./js/jquery.query-2.1.7.js\"></script>\r\n        <script type=\"text/javascript\" src=\"./js/rainbows.js\"></script>\r\n        <!-- // Load Javascipt -->\r\n        <!-- Load stylesheets -->\r\n        <link type=\"text/css\" rel=\"stylesheet\" href=\"css/style.css\" media=\"screen\" />\r\n        <!-- // Load stylesheets -->\r\n\r\n        <!--Esta funcion permite opacar el boton con un hover\r\n        <script>\r\n                $(document).ready(function(){ \r\n");
      out.write("                $(\"#submit1\").hover(\r\n                        function() {\r\n                        $(this).animate({\"opacity\": \"0\"}, \"slow\");\r\n                        },\r\n                        function() {\r\n                        $(this).animate({\"opacity\": \"1\"}, \"slow\");\r\n                        });\r\n                });\r\n        </script>	-->\r\n        <script>\r\n            function login() {\r\n                if (document.loginForm.user.value === \"qmatic@qvision.com.co\" && document.loginForm.password.value === \"secret\") {\r\n                    window.location.href = 'operaciones.jsp';\r\n                } else {\r\n                    document.getElementById('errorMessage').style.display = 'block';\r\n                }\r\n            }\r\n        </script>\r\n    </head>\r\n    <body>\r\n        <div id=\"wrapper\">\r\n            <div id=\"logoBritish\"></div>\r\n            <div id=\"wrappertop\"></div>\r\n            <div id=\"wrappermiddle\">                \r\n                <h2>Training</h2>                \r\n                <form method=\"post\" action=\"GestionSesiones\" name=\"loginForm\" >\r\n");
      out.write("                    <div id=\"username_input\">\r\n                        <div id=\"username_inputleft\"></div>\r\n                        <div id=\"username_inputmiddle\">					\r\n                            <input type=\"email\" name=\"user\" id=\"url\" autocomplete=\"off\" placeholder=\"E-mail\"/>\r\n                            <img id=\"url_user\" src=\"./images/mailicon.png\" alt=\"\"/>					\r\n                        </div>\r\n                        <div id=\"username_inputright\"></div>\r\n                    </div>\r\n                    <div id=\"password_input\">\r\n                        <div id=\"password_inputleft\"></div>\r\n                        <div id=\"password_inputmiddle\">\r\n                            <input type=\"password\" name=\"password\" id=\"url\" placeholder=\"Password\"/>\r\n                            <img id=\"url_password\" src=\"./images/passicon.png\" alt=\"\" />					\r\n                        </div>\r\n                        <div id=\"password_inputright\"></div>\r\n                    </div>\r\n                    <div id=\"submit\" align=\"center\">				\r\n");
      out.write("                        <input name=\"btnLogin\" class=\"btnOperaciones\" style=\"width: 100%\" type=\"submit\" src=\"./images/submit.png\" id=\"submit1\" value=\"Iniciar\" />\r\n                        <!--<input type=\"image\" src=\"./images/submit.png\" id=\"submit2\" value=\"Sign In\">				-->\r\n                    </div>\r\n                </form>\r\n                ");

                    if (request.getAttribute("Error") != null) {
                        String noti = (String) request.getAttribute("Error");
                
      out.write("\r\n                <div id=\"errorMessage\" align=\"center\" style=\"display:block;color:#ff9900;font-family:helvetica, sans-serif;font-size:12px;\">\r\n                    ");
      out.print(noti);
      out.write("\r\n                </div>\r\n                ");

                    }
                
      out.write("\r\n                <div id=\"links_left\">\r\n                    <a href=\"#\">Olvidaste tu Contraseña?</a>\r\n                </div>\r\n                <div id=\"links_right\"><a href=\"#\">Aún no estas Registrado?</a></div>\r\n            </div>\r\n            <div id=\"wrapperbottom\"></div>		\r\n            <div id=\"powered\">\r\n                <p><a href=\"https://britishdigital.us/en/home/\">british digital</a></p>\r\n            </div>\r\n            <div id=\"datos\" align=\"center\">\r\n                <br/>\r\n                <br/>\r\n                <br/>\r\n            </div>\r\n        </div>        \r\n    </body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
